export const posts = [
  {
    postId: 0,
    author: "Ali Hamdan",
    body: "We’ve got to start with Arnie. Hailed for the being the best bodybuilder of all time, if The Terminator trains by these words, then we probably should too. His words cement the belief that we work to improve, not the stay the same",
    image: "/post1.jpg",
    ratting: 3,
    postDate: "01-10-2019",
    topic: "BodyBuilding",
  },
  {
    postId: 1,
    author: "Mark White",
    body: "Yoga is training for soul. Yoga is the journey of the self, through the self, to the self.You cannot always control what goes on outside. But you can always control what goes on inside",
    image: "/post3.jpg",
    ratting: 2,
    postDate: "21-04-2021",
    topic: "yoga",
  },
  {
    postId: 2,
    author: "Andie Shepherd",
    body: "Every competitive powerlifter, marathon runner or triathlete in history started at square one. You shouldn’t expect to deadlift 225 pounds or run 26.2 miles on day one and every exercise-fanatic can relate",
    image: "/post2.jpg",
    ratting: 5,
    postDate: "27-04-2021",
    topic: "fitness",
  },
  {
    postId: 3,
    author: "Kyle SMF",
    body: "Something that women who workout often need to hear, Jessie reminds us that lifting heavy is not just for the boys. Bodybuilding is about a lot more than just looks. Lift to gain confidence. Lift to feel strong. Life to feel amazing",
    image: "/sign.jpg",
    ratting: 2,
    postDate: "21-04-2021",
    topic: "BodyBuilding",
  },
  {
    postId: 4,
    author: "Tom Hanc",
    body: "In a similar vein to ‘nothing great happens in your comfort zone’, this quote is a gentle nudge to challenge ourselves to do things that scare us. Not to be taken too literally, it’s a reminder that bravery can often lead to success.",
    image: "/post5.png",
    ratting: 3,
    postDate: "15-06-2021",
    topic: "BodyBuilding",
  },
  {
    postId: 5,
    author: "Katie NY",
    body: "Gym machines typically overestimate your calorie burn because, hey, big numbers make customers happy. So if you get different numbers from your elliptical and your Fitbit, go with the lower number. But the actual winning move might be to not count activity calories at all.",
    image: "/fit3.jpg",
    ratting: 4,
    postDate: "17-07-2021",
    topic: "fitness",
  },
  {
    postId: 6,
    author: "Martin NY",
    body: "Be where you are, not where you think you should be.The longest journey of any person is the journey inward.It's not about being good at something. It's about being good to yourself.",
    image: "/yoga.jpg",
    ratting: 3,
    postDate: "21-07-2021",
    topic: "yoga",
  },
];
